// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArUESiQdCxxQsrCCVAGVS0_94Vu4IPXIs',
    appId: '1:991869979223:web:8cb4304332597397757112',
    messagingSenderId: '991869979223',
    projectId: 'lenden-a4f36',
    authDomain: 'lenden-a4f36.firebaseapp.com',
    storageBucket: 'lenden-a4f36.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH5w9jCYU5k7HBV8GDyCT-bmK-KJ9EOhs',
    appId: '1:991869979223:ios:f203b2a44869f401757112',
    messagingSenderId: '991869979223',
    projectId: 'lenden-a4f36',
    storageBucket: 'lenden-a4f36.firebasestorage.app',
    iosBundleId: 'com.example.lendentemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArUESiQdCxxQsrCCVAGVS0_94Vu4IPXIs',
    appId: '1:991869979223:web:e762d23bf60ebca8757112',
    messagingSenderId: '991869979223',
    projectId: 'lenden-a4f36',
    authDomain: 'lenden-a4f36.firebaseapp.com',
    storageBucket: 'lenden-a4f36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH5w9jCYU5k7HBV8GDyCT-bmK-KJ9EOhs',
    appId: '1:991869979223:ios:f203b2a44869f401757112',
    messagingSenderId: '991869979223',
    projectId: 'lenden-a4f36',
    storageBucket: 'lenden-a4f36.firebasestorage.app',
    iosBundleId: 'com.example.lendentemp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV6On6xfm5K-RdVxBlAxPJYBG9JxWDRg0',
    appId: '1:991869979223:android:d47e4241a331c127757112',
    messagingSenderId: '991869979223',
    projectId: 'lenden-a4f36',
    storageBucket: 'lenden-a4f36.firebasestorage.app',
  );
}